"""Remove unnecessary fields from Project model, keep only id, project_code, project_name, manager_id

Revision ID: 3094bee02af5
Revises: 9d4eb625166a
Create Date: 2025-06-13 08:44:02.654376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3094bee02af5'
down_revision = '9d4eb625166a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_name', sa.String(length=100), nullable=False))
    op.drop_column('project', 'status')
    op.drop_column('project', 'description')
    op.drop_column('project', 'name')
    op.drop_column('project', 'end_date')
    op.drop_column('project', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('start_date', sa.DATE(), nullable=True))
    op.add_column('project', sa.Column('end_date', sa.DATE(), nullable=True))
    op.add_column('project', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('project', sa.Column('description', mysql.TEXT(), nullable=True))
    op.add_column('project', sa.Column('status', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('project', 'project_name')
    # ### end Alembic commands ###
