"""RM project_name to Technology model

Revision ID: 360a6896748c
Revises: bfbd3d1c7dc6
Create Date: 2025-06-12 23:46:29.488265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '360a6896748c'
down_revision = 'bfbd3d1c7dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technology', schema=None) as batch_op:
        batch_op.drop_column('project_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technology', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_name', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
