"""Remove domains, start_date, and technologies from Project model

Revision ID: 6ad7c6f3cd5f
Revises: 967ab98eaa3e
Create Date: 2025-06-12 23:17:03.031121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ad7c6f3cd5f'
down_revision = '967ab98eaa3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
