"""Remove unnecessary fields from Project model

Revision ID: 967ab98eaa3e
Revises: ab71b56417e5
Create Date: 2025-06-12 23:15:46.657661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '967ab98eaa3e'
down_revision = 'ab71b56417e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('end_date')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('end_date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
