"""Add new fields to Technology model

Revision ID: 9c29f88f0ba1
Revises: 3ad9e0852789
Create Date: 2025-06-12 21:54:39.952820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c29f88f0ba1'
down_revision = '3ad9e0852789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technology', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vendor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manager_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technology', schema=None) as batch_op:
        batch_op.drop_column('manager_name')
        batch_op.drop_column('notes')
        batch_op.drop_column('vendor')
        batch_op.drop_column('project_name')

    # ### end Alembic commands ###
