"""Add description, status, start_date, end_date to Project model

Revision ID: 9d4eb625166a
Revises: d2f77f53dbae
Create Date: 2025-06-13 08:40:26.508621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4eb625166a'
down_revision = 'd2f77f53dbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('project', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('project', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('project', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'end_date')
    op.drop_column('project', 'start_date')
    op.drop_column('project', 'status')
    op.drop_column('project', 'description')
    # ### end Alembic commands ###
