"""Remove manager_name and project_name from Technology model - use relationships instead

Revision ID: b98e1afb98c5
Revises: 3094bee02af5
Create Date: 2025-06-13 09:13:14.080093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b98e1afb98c5'
down_revision = '3094bee02af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technology', 'project_name')
    op.drop_column('technology', 'manager_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technology', sa.Column('manager_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('technology', sa.Column('project_name', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
