"""Add project_name to Technology model

Revision ID: bfbd3d1c7dc6
Revises: 6ad7c6f3cd5f
Create Date: 2025-06-12 23:34:18.288171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfbd3d1c7dc6'
down_revision = '6ad7c6f3cd5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technology', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technology', schema=None) as batch_op:
        batch_op.drop_column('project_name')

    # ### end Alembic commands ###
