"""Add project_name to Technology model

Revision ID: d2f77f53dbae
Revises: 360a6896748c
Create Date: 2025-06-12 23:55:08.698798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f77f53dbae'
down_revision = '360a6896748c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technology', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technology', schema=None) as batch_op:
        batch_op.drop_column('project_name')

    # ### end Alembic commands ###
