"""Add key field to Project model

Revision ID: d9ea9e33be12
Revises: b98e1afb98c5
Create Date: 2025-06-13 10:36:27.788629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ea9e33be12'
down_revision = 'b98e1afb98c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('key', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'project', ['key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_column('project', 'key')
    # ### end Alembic commands ###
