"""add_unique_constraint_component_per_project

Revision ID: f1e124d3f609
Revises: d9ea9e33be12
Create Date: 2025-06-13 15:29:08.795148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e124d3f609'
down_revision = 'd9ea9e33be12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_component_per_project', 'technology', ['name', 'project_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_component_per_project', 'technology', type_='unique')
    # ### end Alembic commands ###
